#ifndef GAME_SERVER_CLASSES_H
#define GAME_SERVER_CLASSES_H

enum
{
	PLAYERCLASS_NONE = 0,
	
	START_HUMANCLASS,
	PLAYERCLASS_MERCENARY,
	PLAYERCLASS_MEDIC,
	PLAYERCLASS_ENGINEER,
	PLAYERCLASS_SOLDIER,
	PLAYERCLASS_NINJA,
	PLAYERCLASS_SCIENTIST,
	END_HUMANCLASS,
	
	PLAYERCLASS_SMOKER,
	PLAYERCLASS_BOOMER,
	PLAYERCLASS_HUNTER,
	PLAYERCLASS_GHOST,
	PLAYERCLASS_WITCH,
	PLAYERCLASS_UNDEAD,
	
	NB_PLAYERCLASS,
};

#endif
